# 使用yaml做配置项
server:
  bind: "0.0.0.0"
  port: 10750
  mode: debug
  cors:
    origins: ["*"]
    methods: ["PUT", "PATCH"]
# 数据库配置项
db:
  type: sqlite # mysql or sqlite
  mysql:
    dbname: "agent"
    password: "root1234"
    username: "root"
    port: 3306
    host: "127.0.0.1"
  sqlite:
    filePath: ./db/agent.db
log:
  # 默认路径是运行程序的目录
  path: ./log/agent
  infoFilename: info.log
  errorFilename: error.log
  maxSize: 10
  maxBackups: 5
  maxAge: 10
  level: info