# 使用yaml做配置项
server:
  bind: "0.0.0.0"
  port: 10750
  mode: debug
  cors:
    origins: ["*"]
    methods: ["PUT", "PATCH"]
# 缓存配置
cache:
  type: memory  # memory 或 redis
  redis:
    addr: "127.0.0.1:6379"
    password: ""
    db: 0
    poolSize: 10
  memory:
    maxCost: 1073741824  # 1GB
    bufferItems: 64
    metrics: false
# 数据库配置项
db:
  type: sqlite # mysql or sqlite
  mysql:
    dbname: "agent"
    password: "root1234"
    username: "root"
    port: 3306
    host: "127.0.0.1"
  sqlite:
    appFilePath: ./db/agent-app.db
    monitorFilePath: ./db/agent-monitor.db
    scriptTaskFilePath: ./db/agent-script-task.db
    agentFilePath: ./db/agent.db
log:
  # 默认路径是运行程序的目录
  path: ./log/agent
  infoFilename: info.log
  errorFilename: error.log
  maxSize: 10
  maxBackups: 5
  maxAge: 10
  level: info
# 通用配置
common:
  # docker-compose 文件存储路径，如果为空则使用当前目录
  composePath: ./compose
  scriptsPath: ./scripts

apiserver:
  http:
    scheme: http
    server: 127.0.0.1:10700
    baseUri: /api/v1